### PR TITLE
BibRank: fix of similar-to-recid result order

### PR DESCRIPTION
**Pull request by pglauner**
https://jenkins.invenio-software.org/job/invenio-master-ondemand/450/testReport/

### CODE REVIEW

**Comment by egabancho** [comment]
If it helps, it's deployed and happily running on CDS

**Comment by jirikuncar** [comment]
@egabancho are you planning to backport it for `maint-1.2` or shall we close it as it is tagged with `v1.3.0`.

**Comment by egabancho** [comment]
Originally it was tagged for `v1.2` but I guess there was no time. It doesn't feel right to close it as it's actually bug fixing.

I think @tiborsimko gave it try in the legacy branch and it was fixing a couple of failing test, I would leave it open.

**Comment by tiborsimko** [comment]
This patch was already merged in another PR: https://github.com/inveniosoftware/invenio/pull/1757

**Pull request closed without merging**
