### PR TITLE
bibknowledge: searchtype parameter addition

### PR DESCRIPTION
**Pull request by pedrogaudencio**
Already merged in master https://github.com/inveniosoftware/invenio/pull/2581.

### CODE REVIEW

**Comment by jirikuncar** [comment]
@hachreak can you check if `searchtype` is supported in new APIs (REST, views). Thanks

**Comment by hachreak** [comment]
We have a `match_type` parameter that works as `searchtype`.

Behaviour:
  if key is specified, use the `matchtype` to customize the query. Else, it doesn't filter by key (returns all).
  The same for value.

https://github.com/inveniosoftware/invenio/blob/pu/invenio/modules/knowledge/models.py#L296

**Comment by jirikuncar** [comment]
@pedrogaudencio is it ready?

**Comment by jirikuncar** [comment]
@pedrogaudencio please rebase now as it should go to `2.0.0`! (cc @kaplun @jalavik @jmartinm)

**Comment by pedrogaudencio** [comment]
@jirikuncar, rebased.

**Pull request merged**
