### PR TITLE
upgrades: recipe fixes

### PR DESCRIPTION
**Pull request by egabancho**
Fixes upgrade recipes for databases coming from the legacy version.

### CODE REVIEW

**Comment by jirikuncar** [comment]
@egabancho as the upgrades has not been officially released you can remove the `FIX` label from commit messages.

**Comment by egabancho** [comment]
:+1:

**Comment by jirikuncar** [comment]
@egabancho it's your turn now. Can you please rebase it? Thanks

**Comment by egabancho** [comment]
done!

**Pull request merged**
