### PR TITLE
WIP search: new facets gui engine

### PR DESCRIPTION
**Pull request by kneczaj**
This pull request is to make a configurable gui for facets with intension to make it work later with Elastic Search.

TODO:
- [x] write tests with Jasmine
- [x] there are some problems with parentheses at query
- [x] with 'links' theme, there are state propagation problems
- [x] rebase with Lars's code
- [x] fix problem with jasmine-jquery
- [x] fix problem with jasmine-ajax
- [x] check with js debug mode off (uglification, bundling etc.)
- [x] "Any" should be translatable ... https://github.com/inveniosoftware/invenio/pull/2281#discussion_r17543212

ElasticSearch comment:
The adaptation should be quite easy, because every facet filter returns a list of checked options for every state, although I think there is no sense to do t without proper elastic search environment.

Alters: https://github.com/jirikuncar/invenio/pull/184, https://github.com/inspirehep/invenio/pull/79

Depends on:
https://github.com/inveniosoftware/invenio/pull/2537

### CODE REVIEW

**Comment by jmartinm** [comment]
@jacquerie will take a look at rebasing it on top of latest pu and checking that everything is working.

**Comment by jacquerie** [comment]
This branch has been rebased on pu in https://github.com/jacquerie/invenio/commits/kneczaj-rebase. The functionality appears to be there (you can test it on http://pcgs2x3160h65:4000), but several tests are failing with obscure errors (you can see those on http://pcgs2x3160h65:4000/jasmine/specrunner).

I will look into this (I suspect some API change happened in Jasmine), but I'm pinging @kneczaj in case he knows the answer off the top of his head.

(CC: @jalavik)

**Comment by jacquerie** [comment]
A few errors might be explained by this: https://github.com/jasmine/jasmine-ajax/issues/88.

BTW, I'm putting my server on another port, so that my machine doesn't get murdered by your incoming connections! The above links will stop working.

**Comment by jacquerie** [comment]
Actually, ALL errors were explained by that API change. Essentially, the `response` method got deprecated in version 2, and was replaced by method `respondWith` in version 3.

**Comment by jirikuncar** [comment]
Work continues in #2752.

**Pull request closed without merging**
