### PR TITLE
docs: fix missing dependencies

### PR DESCRIPTION
**Pull request by danmichaelo**
The list at http://invenio.readthedocs.org/en/latest/getting-started/first-steps.html also includes `subversion`. Is that needed?

### CODE REVIEW

**Comment by jirikuncar** [comment]
@danmichaelo thank you for spotting it. `subversion` is needed for https://github.com/inveniosoftware/invenio/blob/ad39db02238330f419bb73d40d708df059d05cf8/invenio/utils/vcs/svn.py. If you are not using it you don't need it.

Can you please amend commit message to follow Invenio software standard? See an example: `docs: fix missing packages git lib(ffi|ssl)-dev`

--
```console
git commit --amend -m "docs: fix missing packages git lib(ffi|ssl)-dev" -s
git fetch upstream
git rebase -i upstream/master
git push origin patch-1 # -f
```

**Comment by danmichaelo** [comment]
Thanks, think I got it right now.

**Comment by jirikuncar** [comment]
@danmichaelo please rebase on top of latest `master` so we can do `git merge --ff-only upstream/pr/3058`. See my previous comment https://github.com/inveniosoftware/invenio/pull/3058#issuecomment-96949459 with *HOWTO*.

**Comment by danmichaelo** [comment]
Ah, I actually rebased against the master at http://invenio-software.org/repo/invenio , without noticing it was older (why is that?)  Hopefully it's ok now

**Comment by jirikuncar** [comment]
> why is that?

Because we are using GitHub now and we are syncing *nightly?* to legacy location.

**Pull request merged**
