### PR TITLE
deposit: separation of typeahead initialization

### PR DESCRIPTION
**Pull request by jmartinm**
* Separates connecting events and initializing typeahead so that
  one can set up a custom typeahead with all the events connected
  with the form.

Co-authored-by: Kamil Neczaj <kamil.neczaj@cern.ch>
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
Rebased

**Comment by jirikuncar** [comment]
Please amend commit message `##2442 -> #2442`, copyright year and you can add me as reviewer. Thanks!

**Comment by jmartinm** [comment]
Done

**Comment by jmartinm** [comment]
Updated. Travis does not complain any more.

**Pull request merged**
