### PR TITLE
Sentry: enhance logging

### PR DESCRIPTION
**Pull request by egabancho**

### CODE REVIEW

**Comment by kaplun** [comment]
@egabancho  is this deployed on CDS?

**Comment by egabancho** [comment]
Yes

**Comment by kaplun** [comment]
I like it! :shipit: 
Can you rebase on top of latest legacy and add `Reviewed-by: me`?

**Comment by tiborsimko** [comment]
Thanks, merged as:

- 67cd1bca8ffced7c502119533c93878bd9c65a6f WebStyle: logging level on some IOError
- 5f7b20d88d9052e654f465ffb6b332eef843dc30 WebStyle: default logging level for SERVER_RETURN
- 2ae9fdd24c89f677ca47bcaf83c44d8ae631374a errorlib: sentry logging enhancement

**Pull request closed without merging**
