### PR TITLE
WebStyle: wsgi handler IP parser enhancement

### PR DESCRIPTION
**Pull request by egabancho**
- BETTER Cleans the port from the user's IP preventing issues in
  future manipulations of it.
- Improves PEP8 code style.

Signed-off-by: Esteban J. G. Gabancho esteban.gabancho@gmail.com

### CODE REVIEW

**Comment by jirikuncar** [comment]
`s/ENHANCEMENT/BETTER/`, `s/kwalitee fixes./Improves PEP8 code style./`

**Comment by egabancho** [comment]
:+1:

**Comment by kaplun** [comment]
@egabancho can't remember what we said IRL. I think this PR was good, although it was not easy to distinguish the feature changes from PEP8 ones. Would you have a chance to split these in 2 commits?

**Comment by egabancho** [comment]
You are right @kaplun!

**Comment by kaplun** [comment]
Can you rebase it and add `Reviewed-by: me`?

**Comment by egabancho** [comment]
Done!

**Comment by tiborsimko** [comment]
@egabancho The kwalitee part of the PR does not apply cleanly to `maint-1.2`, so I left it out. Since it does only kwalitee amendments, this should be accepable... and we can always put it onto `legacy` later, if wanted. OK with you?

**Comment by tiborsimko** [comment]
Closed by https://github.com/inveniosoftware/invenio/pull/3728.

**Pull request closed without merging**
