### PR TITLE
WebSubmit: fix for Upload_Files element example

### LINKED ISSUE #2610: WebSubmit: Upload_Files element example does results in a 500er (Version 1.1.4)
Hi, 
in Invenio 1.1.4 the Example Response Element "Upload_Files" contains example code, which should be cloned and customized according to the documentation.
However, the code produces a 500er server error, since the python os module which is used in the
line
indir = ParamFromFile(os.path.join(curdir,...) and following lines has not been loaded.
Adding
import os
before these lines fixes this.
Regards
 Martin

### PR DESCRIPTION
**Pull request by martinkoehler**
import os
to various sql statements in building the example Upload_Files interface for the demo site
closes #2610

### CODE REVIEW

**Comment by tiborsimko** [comment]
We'd need to create upgrade recipes. @kaplun Do I understand it right that you started to look at this?

**Comment by tiborsimko** [comment]
@kaplun Any updates on this?

**Comment by kaplun** [comment]
@tiborsimko nope. Actually at that time I had to postpone checking the PR, and then I got moved to something else. Right now I don't have an easy way to test this. Is there any volunteer to take over this PR integration?

**Comment by tiborsimko** [comment]
> nope

Thanks for the quick reply. I guess I'll move the milestone to v1.1.8 then, since v1.1.7 is going to be released in the next few days... just doing some final cleanup.

> Right now I don't have an easy way to test this.

You can use `vagrant` to get an Invenio 1.1 demo site up and running easily:

```console
$ git checkout maint-1.1
$ vagrant up --no-parallel
$ vagrant ssh web -c 'source .inveniorc && /vagrant/scripts/create-instance.sh'
$ vagrant ssh web -c 'source .inveniorc && /vagrant/scripts/populate-instance.sh'
$ firefox http://192.168.50.10/record/1
$ vagrant ssh web -c 'source .inveniorc && sudo -u www-data /opt/invenio/bin/inveniocfg --run-unit-tests'
$ vagrant ssh web -c 'source .inveniorc && sudo -u www-data /opt/invenio/bin/inveniocfg --run-regression-tests --yes-i-know'
```

**Pull request closed without merging**
