### PR TITLE
legacy: hepdata removal

### PR DESCRIPTION
**Pull request by kaplun**
* INCOMPATIBLE Removes legacy hepdata module. (addresses #3233)

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@kaplun  please add `Reviewed-by: me`, rebase and :shipit:

**Comment by kaplun** [comment]
Done.

**Comment by kaplun** [comment]
Mmh. wait there are some copyrights not updated.

**Comment by kaplun** [comment]
OK really done

**Pull request merged**
