### PR TITLE
Fix master after search replacement

### PR DESCRIPTION
**Pull request by hachreak**
* Removes tests to fix bibsort removal on d74e93 commit.
  (addresses #3233)

* Fixes BibRank removal on d74e93. (addresses #3233)

* Fixes warning on module externalization in 174b09.

* Adds elasticsearch and invenio_records in travis configuration.

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by crepererum** [comment]
Just want to mention that this PR does not recover master fully. There are still tests failing.

**Comment by hachreak** [comment]
@crepererum now it works fine..
I'm waiting @tiborsimko reviews the code to merge into the master.

**Comment by crepererum** [comment]
:clap:

**Comment by tiborsimko** [comment]
LGTM, tested, merging...

**Pull request merged**
