### PR TITLE
WebStyle: CKEditor update

### PR DESCRIPTION
**Pull request by switowski**
- BETTER Updates the CKEditor to version 4.5.3
- INCOMPATIBLE Removes the skin config variable (since there are new
  skins)

Signed-off-by: Sebastian Witowski witowski.sebastian@gmail.com

### CODE REVIEW

**Comment by switowski** [comment]
@tiborsimko could you please download this version of CKEditor: http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.5.3/ckeditor_4.5.3_full.zip
and put it in the http://invenio-software.org/download/ckeditor/
directory ?

**Comment by switowski** [comment]
CDS PR https://github.com/CERNDocumentServer/invenio/pull/145

**Comment by tiborsimko** [comment]
@switowski Download done, there is now `ckeditor_4.5.3.zip` file available there.

WRT your commit log message, if you put two different points, there will be two different news items appearing in two different sections of the release notes; so it would be good to be more explicit with the second one:

```
* BETTER ...

* INCOMPATIBLE Removes the CKEditor skin configuration variable...
```

However, I guess we can simply make this as one release news item only, something like:

```
* BETTER Upgrades CKEditor to version 4.5.3.  Note that the skin 
  configuration variable was removed because of new skins.
```

**Comment by switowski** [comment]
@tiborsimko you are right, I have fixed the commit message :)

**Pull request closed without merging**
