### PR TITLE
records: exposing record metadata revisions

### PR DESCRIPTION
**Pull request by bogdan-kulynych**
(addresses #1990)

* Extends `get_record` with optional `revision` parameter
* Exposes revision for record information (metadata) tab
* Adds a config variable CFG_RECORD_REVISION_URL_PARAMETER
  with default value of "revision"

Signed-off-by: Bogdan Kulynych <bogdan.kulynych@gmail.com>

### CODE REVIEW

**Comment by lnielsen** [comment]
@tiborsimko Invenio code base have moved quite far since this PR was opened, and given the new rewrite of data model and search I think it will be likely hard to reintegrate this, so would it be ok to close the PR as someday so that we can still look up the code if we need it in the future.

**Comment by egabancho** [comment]
Related with #3129

**Comment by tiborsimko** [comment]
Another issue is the relation to forthcoming DIP store that will allow to archive more historical formats than just JSON or master ones.  (E.g. slave BibTeX format, see discussion in #1990). Hence some parts of this PR can be recycled now in @egabancho's branch, and wider user-serving parts could be revived once we start with the DIP store.

**Comment by jirikuncar** [comment]
Implementation should be adapted in new *Invenio-Records* module (https://github.com/inveniosoftware/invenio-records/issues/10).

**Pull request closed without merging**
