### PR TITLE
scripts: update of bibliographic jsonschema to v1.0.2

### LINKED ISSUE #3761: Cannot run docker container
Hi,

I am trying to build a docker container for testing using instructions for version 3.0: http://inveniosoftware.org/gettingstarted
I am using v3.0.0a4 as master did not work for me. I had to apply fixes mentioned in #3753 and #3737. However I have encountered a new problem:

```
$ docker-compose run --rm web ./scripts/populate-instance.sh 
Creating database postgresql+psycopg2://invenio3:dbpass123@postgresql:5432/invenio3
Creating all tables!
  [####################################]  100%
Created all tables!
User created successfully.
{'active': True, 'password': '****', 'email': u'info@inveniosoftware.org'}
Traceback (most recent call last):
  File "/home/invenio/.virtualenvs/invenio3/bin/invenio3", line 11, in <module>
    load_entry_point('invenio3', 'console_scripts', 'invenio3')()
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/cli.py", line 374, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/flask/cli.py", line 251, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_records/cli.py", line 117, in create
    click.echo(Record.create(record, id_=id_).id)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_records/api.py", line 193, in create
    record.validate(**kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_records/api.py", line 140, in validate
    return _records_state.validate(self, self['$schema'], **kwargs)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_records/ext.py", line 58, in validate
    **kwargs
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/invenio/.virtualenvs/invenio3/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: [u'ALEPH Collaboration'] is not of type u'string'

Failed validating u'type' in schema[u'allOf'][9][u'properties'][u'added_entry_corporate_name'][u'items'][u'properties'][u'miscellaneous_information']:
    {u'type': u'string'}

On instance[u'added_entry_corporate_name'][0][u'miscellaneous_information']:
    [u'ALEPH Collaboration']
```

### PR DESCRIPTION
**Pull request by dinosk**
Introduces issue [#189](https://github.com/inveniosoftware/dojson/issues/189) in dojson, fixed in PR [#190](https://github.com/inveniosoftware/dojson/pull/190). Should be merged afterwards.

* FIX Updates bd-v1.0.0.json to bd-v1.0.2.json.
  (closes #3761)

Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>

### CODE REVIEW

**Comment by nharraud** [comment]
@dinosk can you start the first bullet point with "FIX" as it is a bugfix.

**Comment by tiborsimko** [comment]
Note that upgrading schema would necessitate also:

- to remove the pinning of `dojson` in installation scripts[*];
- to remove the pinning of `invenio-marc21` in installation scripts[*];
- most probably, to update Elasticsearch mappings in the invenio-marc21 package and to release it;
- to upgrade lowest required versions of `dojson`, `invenio-marc21` in Invenio's `setup.py` after releasing updated versions.

This is roughly what I planned to do after quick-fixing the installation issues in https://github.com/inveniosoftware/invenio/pull/3768.

@dinosk Have you checked whether the demo site search works well with your PR? I guess there would be troubles unless we update the Elasticsearch mapping in invenio-marc21...

```console
$ docker-compose build
$ docker-compose up -d
$ docker-compose run --rm web ./scripts/populate-instance.sh
$ firefox http://127.0.0.1/records/1
$ firefox http://demo3.inveniosoftware.org/search?q=ellis
```

P.S. Anyway we may also wait and update these matters in flavours (ILS, RDM...)

[*] See:

```console
$ grep -A 2 FIXME scripts/create-instance.sh 
# FIXME upgrade to dojson 1.3.0 WRT mappings and unpin
pip install dojson==1.2.1
pip install invenio-marc21==1.0.0a3
```

**Comment by dinosk** [comment]
@tiborsimko it won't be able to run scripts/populate-instance.sh, as I upgraded dojson to 1.3.0 to get bd-v1.0.2.json.

**Comment by nharraud** [comment]
Closed in favor of 72817e1a1dafa37f1b14d46c6a70e08d7de89661

**Pull request closed without merging**
