### PR TITLE
Bibformat: add --missing-formats option

### PR DESCRIPTION
**Pull request by switowski**
* Replaces the --no-missing option with --missing-formats, so by default
  missing formats are not generated.

Signed-off-by: Sebastian Witowski <sebastian.witowski@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
Since this branch is proposing a change in the default behavior I think a dummy upgrade recipe should be added spitting out a warning for the admin to amend his/her bibreformat scheduled tasks to add `--missing-formats`. Additionally the default documentation in Invenio advises to just schedule `bibreformat -s5m` and this should do the right thing.

**Comment by switowski** [comment]
@kaplun hmm, that's true. I have changed the code, so now we no longer need any additional changes.
Now, we will skip formatting missing cache if there is a pattern, collection, id, etc. specified, but we will still generate missing cache if the bibformat is run without parameters (or with format parameter).

**Comment by kaplun** [comment]
:shipit:

**Comment by kaplun** [comment]
@tiborsimko this micro-patch can also go into 1.2.0 IMHO

**Comment by tiborsimko** [comment]
- [ ] Please update the commit log message to put the FIX label in front, so that this will be well reported in the automatically generated release notes.

- [ ] Please add `Reviewed-by: Samuele Kaplun <samuele.kaplun@cern.ch>`

**Comment by switowski** [comment]
@tiborsimko Done

**Comment by egabancho** [comment]
Running on CDS

**Comment by kaplun** [comment]
Have to be rebased though...

**Comment by tiborsimko** [comment]
Cherry-picked into `maint-1.2` as 2eb74cc7aa7bd35a76bf991943264aee08fc1c05.

**Pull request closed without merging**
