### PR TITLE
legacy: removal of hstRECORD table

### PR DESCRIPTION
**Pull request by jirikuncar**
* INCOMPATIBLE Removes legacy hstRECORD table definition.

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

### CODE REVIEW

**Comment by egabancho** [comment]
Naive question, how are we going to keep the different versions of records?

**Comment by jirikuncar** [comment]
@egabancho on `before_update` we create a copy or we use versionable behavior from SQLAlchemy.

**Comment by kaplun** [comment]
Other naive question: if you delete the model, how will we be able to migrate the history to the new support that will come?

**Comment by egabancho** [comment]
The model is deleted, but the table will remain there :wink:

**Comment by kaplun** [comment]
Aren't models needed for querying the table? Or is done directly with `run_sql`?

**Comment by egabancho** [comment]
@kaplun I guess `run_sql` should be good enough

**Pull request merged**
