### PR TITLE
jsonalchemy: fix setting default value for dicts

### PR DESCRIPTION
**Pull request by MSusik**

### CODE REVIEW

**Comment by MSusik** [comment]
@egabancho Fix for one of the errors that I was mentioning. Notice that it is still wrong from the implementation point of view, but I don't know what exactly is the purpose of function. At least now it works from API.

**Comment by MSusik** [comment]
Added another bugfix.

**Comment by jirikuncar** [comment]
Can you create patch for https://github.com/inveniosoftware/jsonalchemy? Thanks

**Comment by MSusik** [comment]
@jirikuncar  Firstly I'd like to have this PR accepted. If the code is fine, after merge I will create a PR to the new package.

**Comment by jirikuncar** [comment]
@MSusik I will accept it when I see new PR to `jsonalchemy`.

**Comment by kaplun** [comment]
@jirikuncar is pu branch already depending on the separate JSONAlchemy package?

**Comment by MSusik** [comment]
@kaplun I think I can answer it: no.

**Comment by jirikuncar** [comment]
I'm going to remove the JSONAlchemy package from Invenio very soon. I'm not going to accept any patches for `invenio.modules.jsonalchemy` unless the same patch is created for separate `jsonalchemy` package too.

**Comment by jirikuncar** [comment]
@kaplun @MSusik moreover the PR is still missing review from @egabancho.

**Comment by MSusik** [comment]
Added test.

**Comment by MSusik** [comment]
Moved the PR to https://github.com/inveniosoftware/invenio/pull/2883
Also, I removed the commit which was suggesting a change in the code where Esteban already changed it.

**Pull request closed without merging**
