### PR TITLE
BibDocFile: make filenames url safe

### PR DESCRIPTION
**Pull request by drjova**
* IMPROVEMENT Makes filenames url safe.

Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by jirikuncar** [comment]
Shouldn't this go to `maint-1.2`?

**Comment by kaplun** [comment]
:shipit: I think it's good to go!

**Comment by tiborsimko** [comment]
- [ ] Please update the commit log message to put BETTER instead of IMPROVEMENT, and please expand the phrase a bit.  (E.g. "Better escapes file names in document URLs.")

- [ ] Please add `Reviewed-by: Samuele Kaplun <samuele.kaplun@cern.ch>`

**Comment by drjova** [comment]
:+1: done thanks!

**Comment by tiborsimko** [comment]
Cherry-picked into `maint-1.2` as 244457fe9dfbeb6c8fdeac186d03c878655affe6.

**Pull request closed without merging**
