### PR TITLE
deposit: DynamicItemWidget remove button fix

### PR DESCRIPTION
**Pull request by jmartinm**
* Do not show the remove button on the first item of a
  DynamicItemWidget.

Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
Can you have a look @lnielsen ?

**Comment by lnielsen** [comment]
In the airport, so didn't have much time to look, but I would think it makes sense to have a remove button even for the first line?

**Comment by jmartinm** [comment]
Well it looks like a bug if there is only one element:



But I see your point, if there are several elements in the list, then it can make sense to remove the first element...

**Comment by jmartinm** [comment]
Closing this as for the moment I am not sure what the best approach is.

**Pull request closed without merging**
