### PR TITLE
Master xm field

### PR DESCRIPTION
**Pull request by egabancho**

### CODE REVIEW

**Comment by egabancho** [comment]
Running on CDS

**Comment by tiborsimko** [comment]
@egabancho What is the purpose of this new XMF format exactly? The use case to "output only these MARC tags" is already supported by the regular XM format, for example hitting:

```
http://demo.inveniosoftware.org/record/1?of=xm&ot=001,100,245
```

returns only wanted fields:

```
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns="http://www.loc.gov/MARC21/slim">
<record>
  <controlfield tag="001">1</controlfield>
  <datafield tag="100" ind1=" " ind2=" ">
    <subfield code="a">Photolab</subfield>
  </datafield>
  <datafield tag="245" ind1=" " ind2=" ">
    <subfield code="a">ALEPH experiment: Candidate of Higgs boson production</subfield>
  </datafield>
</record>
</collection>
```

**Comment by egabancho** [comment]
@tiborsimko honestly, I don't know. I didn't check the content of the branch, just put it here so it didn't get lost.

I'll take a look what is the final purpose of it in CDS, if any!

**Comment by egabancho** [comment]
see https://github.com/inveniosoftware/invenio/pull/2769#issuecomment-203902710

**Pull request closed without merging**
