### PR TITLE
BibFormat: adds support for the Google +1 button

### LINKED ISSUE #1296: BibFormat: add support for the Google +1 button
Originally by *[nkasioum (@kasioumis)](https://github.com/kasioumis)* on 2013-02-12

Along with the other bookmarking services, support for the Google +1 button could be offered to the user.

### PR DESCRIPTION
**Pull request by kasioumis**
(closes #1296)

### CODE REVIEW

**Comment by jirikuncar** [comment]
@kasioumis please fix the commit message (no verbs in title, `NEW` or `BETTER` label for bullet point).

**Comment by kasioumis** [comment]
@jirikuncar Sure :-) Is it better now?

**Comment by jirikuncar** [comment]
see http://invenio.readthedocs.org/en/latest/technology/git.html#r2a-commit-message-format + https://cds.cern.ch/record/2060037?ln=en

**Comment by kasioumis** [comment]
@jirikuncar The latest update should do it :-) Let me know if not.

**Comment by egabancho** [comment]
I think you need to put the `closes` in the same together with the bullet point that explains a bit what is closed, i.e. `git log` if you search for `closes`

```
commit fa009b4397c2749dd9cec1c0b877d4d9524b7b73
Author: Sebastian Witowski <sebastian.witowski@cern.ch>
Date:   Fri Oct 25 11:32:09 2013 +0200

    BibDocFile: add download all files in BibRecDoc

    * NEW Adds a new functionality that permits to obtain tarball of all
      the files associated with a record. For example,
      `/record/123/files/allfiles` includes all the original files in the
      tarball, `/record/123/files/allfiles-small` includes only icons of 180
      pixels, etc. The behaviour is governed by internal configuration
      variable `CFG_BIBDOCFILE_STREAM_ARCHIVE_FORMATS`.  (closes #1673)

    Signed-off-by: Sebastian Witowski <sebastian.witowski@cern.ch>
```

Now it might be to much, but in the future (of legacy?) it would be nice if the pep8 enhancements are in a separated commit, it will help in case we need to run [git bisect](https://git-scm.com/docs/git-bisect), i.e.

```
commit 763cd76e3076883d02121029158ff09b205a44ce
Author: Federico Poli <federico.poli@cern.ch>
Date:   Fri May 9 13:34:56 2014 +0200

    WebSearch: new Journal Hint Service

    * Adds the Journal Hint Service, that displays
      'Were you looking for a journal reference? Try: <link>'
      when the user search for a raw journal reference.
      (PR #2352)

    * Adds unit and regression tests for the new search service.

    * Adds two unit tests to `search_from_reference`, just to be sure that
      it accepts unicode.

    Signed-off-by: Federico Poli <federico.poli@cern.ch>
    Reviewed-by: Samuele Kaplun <samuele.kaplun@cern.ch>
    Reviewed-by: Tibor Simko <tibor.simko@cern.ch>

commit be89b95e31a7d3b6505400d5a0d7c61eae1c27b6
Author: Federico Poli <federico.poli@cern.ch>
Date:   Tue Aug 5 13:52:00 2014 +0200

    WebSearch: kwalitee fix

    * Runs `autopep8` on `websearch_services_regression_tests.py`.
      (PR #2352)

    Signed-off-by: Federico Poli <federico.poli@cern.ch>
    Tested-by: Tibor Simko <tibor.simko@cern.ch>
```

But probably you can still add a new bullet to your commit, something like `* kwalitee improvements.`

Last but not least, probably you want to add 

```
Signed-off-by: Nikolaos Kasioumis <nikolaos.kasioumis@cern.ch>
```
(Note if you do `git commit -s` it will add the signature for you)

**Comment by kasioumis** [comment]
@egabancho @jirikuncar thanks for the suggestions guys, I think I got it right this time :-)

**Comment by egabancho** [comment]
Maybe you can also fix some of the [kwalitee errors](http://kwalitee.invenio-software.org/inveniosoftware/invenio/branches/86006a7d49191ddbf3405504603cc0a8da5cb4d8/kasioumis:legacy-google-plus-bookmark)
Some things must be fixed before this gets integrated like `4: L102 copyright year is outdated, expected 2015 but got 2011`
Others are just nice to have/do since you are doing the `pep8` and `pep257` already :smiley: 

BTW all your commits in Invenio are signed with ` Nikolaos Kasioumis <nikolaos.kasioumis@cern.ch>` maybe you want to change your `.gitconfig` :wink:

**Comment by kasioumis** [comment]
@egabancho Success! No more kwalitee errors. Although, I didn't get why this wouldn't be integrated otherwise. I thought the idea was to not to introduce new kawlitee errors. As long as the error count is equal or lower to the one before the commit, then it should be accepted, right? I mean, I like fixing kwalitee erros, but I'd rather focus on the Google +1 functionality on this commit.

@egabancho Also, I'd rather use my personal e-mail from now on in my signatures. I've amended my `.gitconfig` long ago to mention `Nikos Kasioumis <kasioumis@gmail.com>` instead of `Nikolaos Kasioumis <nikolaos.kasioumis@cern.ch>`. Is that what you mean? Do you think that is an issue? I don't mind having a different signature, I wanted to change it and it would happen eventually...

**Comment by egabancho** [comment]
> Although, I didn't get why this wouldn't be integrated otherwise. I thought the idea was to not to introduce new kawlitee errors. As long as the error count is equal or lower to the one before the commit, then it should be accepted, right? I mean, I like fixing kwalitee erros, but I'd rather focus on the Google +1 functionality on this commit.

Some of them are mandatory, like the one for the copyright, the rest are just nice to have.

>Also, I'd rather use my personal e-mail from now on in my signatures. I've amended my .gitconfig long ago to mention Nikos Kasioumis <kasioumis@gmail.com> instead of Nikolaos Kasioumis <nikolaos.kasioumis@cern.ch>. Is that what you mean? Do you think that is an issue? I don't mind having a different signature, I wanted to change it and it would happen eventually...

It was just to let you know, I made this mistake in the past and some of my commits are with a different email address :wink:

**Comment by tiborsimko** [comment]
Thanks, merged as a018bdbb2ca24f263d8a389a642d7d8a31f9e137.

**Pull request closed without merging**
