### PR TITLE
legacy: BibAuthorList removal

### PR DESCRIPTION
**Pull request by hachreak**
* INCOMPATIBLE Removes legacy BibAuthorList module together with ported
  'authorlist' module.  (addresses #3233)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by hachreak** [comment]
@jirikuncar 

`git grep -i authorlist`

```
invenio/legacy/oaiharvest/utils.py:def create_authorlist_ticket(matching_fields, identifier, queue):
invenio/legacy/oaiharvest/utils.py:    in extracted authors from collaboration authorlists.
invenio/legacy/oaiharvest/utils.py:Harvested record with identifier %(ident)s has had its authorlist extracted and contains some UNDEFINED affiliations.
invenio/legacy/websession/templates.py:                if action == "runauthorlist":
invenio/legacy/websession/templates.py:                    tmp_out += """<br />&nbsp;&nbsp;&nbsp; <a href="%s/authorlist/">%s</a>""" % (CFG_SITE_URL, _("Run Author List Manager"))
invenio/modules/access/local_config.py:             ('authorlistusers', 'Users who can user Authorlist tools', 'deny all'),
invenio/modules/access/local_config.py:               ('runauthorlist', 'run Authorlist tools', '', 'no'),
invenio/modules/access/local_config.py:             ('authorlistusers', 'runauthorlist', {}),
invenio/modules/oaiharvester/tasks/postprocess.py:    "<collaborationauthorlist.*?>.*?</collaborationauthorlist>", re.DOTALL)
invenio/modules/oaiharvester/tasks/postprocess.py:    """Perform the special authorlist extraction step.
invenio/modules/oaiharvester/tasks/postprocess.py:            ) or "authorlist2marcxml.xsl"
invenio/modules/oaiharvester/tasks/postprocess.py:            authorlist_record = create_records(authors)
invenio/modules/oaiharvester/tasks/postprocess.py:            if len(authorlist_record) == 1:
invenio/modules/oaiharvester/tasks/postprocess.py:                if authorlist_record[0][0] is None:
invenio/modules/oaiharvester/tasks/postprocess.py:                    eng.log.error("Error parsing authorlist record for id: %s" % (
invenio/modules/oaiharvester/tasks/postprocess.py:                authorlist_record = authorlist_record[0][0]
invenio/modules/oaiharvester/tasks/postprocess.py:            translate_fieldvalues_from_latex(authorlist_record, '100', code='a')
invenio/modules/oaiharvester/tasks/postprocess.py:            translate_fieldvalues_from_latex(authorlist_record, '700', code='a')
invenio/modules/oaiharvester/tasks/postprocess.py:                          + record_xml_output(authorlist_record) + '</collection>'
invenio/modules/upgrader/upgrades/invenio_2013_09_26_webauthorlist.py:    return "Tables for new webauthorlist module"
```

I need to remove something from them connected with authorlist?

**Comment by jirikuncar** [comment]
All except `invenio/modules/upgrader/upgrades/invenio_2013_09_26_webauthorlist.py`

**Comment by jalavik** [comment]
@hackreak @jirikuncar Can you undo all the changes done to legacy oaiharvest and oaiharvester in this PR? You see, those parts have nothing to do with the authorlist module that is removed. Its something else. (I won't be back until Wednesday to fix it myself ;-) ). Thanks!

**Comment by jirikuncar** [comment]
@jalavik I'm sorry about that. I have reverted it in 78fa942.

**Comment by jalavik** [comment]
@jirikuncar No worries. Thanks for the revert!

**Pull request merged**
