### PR TITLE
legacy: ANSI_QUOTES setting on second try

### PR DESCRIPTION
**Pull request by jalavik**
* FIX Sets the ANSI_QUOTES setting also on the second attempt
  to connect to the database in case of a lost connection.

Signed-off-by: Jan Aage Lavik <jan.age.lavik@cern.ch>

### CODE REVIEW

**Comment by jalavik** [comment]
Just discovered this issue. Added it to the current milestone due to its small size.

**Comment by jirikuncar** [comment]
:shipit: 

--
fyi @hachreak

**Comment by jirikuncar** [comment]
@jalavik since it has been introduced in 79741888d8e71b22e704a30038f9857d90a38590 I would remove `FIX` label from the commit message. Thanks a lot for yet another catch :+1:

**Comment by tiborsimko** [comment]
> @jalavik since it has been introduced in 7974188 I would remove FIX label from the commit message. 

... or we can amend the original commit message here (via AMENDS 7974188) and also fix the (invalid) COMPATIBILITY label at the same time?

**Comment by jirikuncar** [comment]
>  fix the (invalid) COMPATIBILITY label at the same time?

:+1:

**Comment by jalavik** [comment]
So how would the commit message look with these considerations in mind?

```
legacy: ANSI_QUOTES setting on second try

* BETTER Supports database creation on PostgreSQL server.

* Enables 'sql_mode' as 'ansi_quotes' for quotes compatibility for MySQL.

* AMENDS 7974188
```

**Comment by jirikuncar** [comment]
IMHO @tiborsimko meant `s/COMPATIBILITY/INCOMPATIBLE/`.

**Comment by jalavik** [comment]
So, something like this?

**Comment by jirikuncar** [comment]
:+1:

**Pull request merged**
