### PR TITLE
global: super call addition to SmartDict

### PR DESCRIPTION
**Pull request by Theer108**
I need this super call for proper inheritance in invenio-records.

Signed-off-by: Łukasz Chrząszcz <l.chrzaszcz@gmail.com>

### CODE REVIEW

**Comment by egabancho** [comment]
What about changing the commit message to `utils: super call added to SmartDict`

I guess we can make this PR for `maint-2.0`, can you rebase on top of it instead of `master`? (don't close this PR just rebase)

And you can add `Reviewed-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>` too :wink:

**Comment by jirikuncar** [comment]
`s/added/addition/` - no verbs on first line - http://invenio.readthedocs.org/en/latest/developers/git-workflow.html?highlight=git#r2-remarks-on-commit-log-messages - we should mention this change with `BETTER` label

**Comment by egabancho** [comment]
ping @jirikuncar

**Comment by jirikuncar** [comment]
@Theer108 please use `global` component and rebase. Thanks

**Comment by Theer108** [comment]
Done

**Comment by jirikuncar** [comment]
> I guess we can make this PR for `maint-2.0`, can you rebase on top of it instead of `master`? (don't close this PR just rebase)

@Theer108 see https://github.com/inveniosoftware/invenio/pull/3386#issuecomment-123626931 (cc @egabancho)

**Comment by Theer108** [comment]
Done again

**Pull request merged**
