### PR TITLE
legacy: dbquery import fix

### LINKED ISSUE #3089: legacy: run_sql problems with quotes
After 79741888d8e71b22e704a30038f9857d90a38590 there are several problems with running programs such as bibsched:

```shell
$ bibsched
...
File "/home/jlavik/envs/pu/src/invenio/invenio/legacy/dbquery_mysql.py", line 277, in run_sql
    except (OperationalError, InterfaceError):
NameError: global name 'OperationalError' is not defined
```
PS: Perhaps pylint -E could have catched this initial error?

I fixed the import, but for bibsched troubles were not over:

```
  File "/home/jlavik/envs/pu/src/invenio/invenio/legacy/bibsched/cli.py", line 378, in fetch_debug_mode
    r = run_sql('SELECT value FROM schSTATUS WHERE name = "debug_mode"')
  File "/home/jlavik/envs/pu/src/invenio/invenio/legacy/dbquery_mysql.py", line 277, in run_sql
    rc = cur.execute(sql, param)
  File "/home/jlavik/envs/pu/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/jlavik/envs/pu/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'debug_mode' in 'where clause'")
```

I tried fixing these, but its simply too much. Probably due to ansi mode quotes? I suggest in the meantime to revert 79741888d8e71b22e704a30038f9857d90a38590

@hachreak @jirikuncar

### PR DESCRIPTION
**Pull request by hachreak**
* Fixes imports on dbquery legacy interface. (addresses #3089)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@hachreak does it really solve the second part of the issue #3089?
```
  File "/home/jlavik/envs/pu/src/invenio/invenio/legacy/bibsched/cli.py", line 378, in fetch_debug_mode
    r = run_sql('SELECT value FROM schSTATUS WHERE name = "debug_mode"')
  File "/home/jlavik/envs/pu/src/invenio/invenio/legacy/dbquery_mysql.py", line 277, in run_sql
    rc = cur.execute(sql, param)
  File "/home/jlavik/envs/pu/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/jlavik/envs/pu/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1054, "Unknown column 'debug_mode' in 'where clause'")
```

**Comment by hachreak** [comment]
maybe because of `ansi_quote` is active now? If it's true, I should change `"` with `'` for value on any sql query to fix it! (where is the `scared` emoticon when I need it? XD)

**Comment by jirikuncar** [comment]
I have found few candidates to be fixed: `git grep "VALUES .*\"[^\"]\{1,\}\""` and `git grep "WHERE .*=\"[^\"]\{1,\}\""`. It's **not** complete list but for sure good start.

--
PS: :fearful:

**Comment by hachreak** [comment]
Others candidates: `git grep "WHERE .*\"[^\"]\{1,\}\""`

p.s. thanks for the emoticon... XD

**Comment by jirikuncar** [comment]
@hachreak can you just replace ` (closes #3089)` to ` (addresses #3089)` so we can merge it?

**Comment by hachreak** [comment]
done

**Pull request merged**
