### PR TITLE
WebStyle: improved HTTP error code

### PR DESCRIPTION
**Pull request by kaplun**
- Improves reporting of HTTP error codes in ways that can help
  crawlers correctly analyzing the available pages.

Signed-off-by: Samuele Kaplun samuele.kaplun@cern.ch

### CODE REVIEW

**Comment by jirikuncar** [comment]
Is it really enhancement or just bugfix? Does it worth it backporting it for `maint-1.2`?

**Comment by kaplun** [comment]
Eh. It's a bugfix but an important one from a service POW: without it Google would happily index all deleted records and cluttering the index with "this record has been deleted" or similar.

**Comment by jirikuncar** [comment]
@kaplun I have changed the labels. Can you then re-submit the patch for `maint-1.2` (or at least rebase on top of it)?

**Comment by kaplun** [comment]
I have rebased against maint-1.2

**Comment by jirikuncar** [comment]
@kaplun can you also add `BETTER` in commit message so it is easier to generate release notes? Thanks

**Comment by kaplun** [comment]
Sure! Done.

**Comment by jirikuncar** [comment]
@kaplun the regression tests are failing :(

**Comment by kaplun** [comment]
Weird! They were not failing before rebasing, but they failures seem to make sense (I mean like the tests should simply need to be amended).

Mmh, given that, maybe it's simply better to restore the original branch against `legacy` and no longer try to have them against `maint-1.2`.

**Comment by jirikuncar** [comment]
@kaplun or try to submit new PR for maint-1.2 directly.

**Comment by kaplun** [comment]
This patch against `maint-1.2` is what is not passing the tests, and I don't have resources to fix them. I restored this PR against `legacy` as it was originally intended. Let's see if regression tests now pass (as before). Otherwise we shall blame it on yesterday Travis's blackout.

**Comment by tiborsimko** [comment]
I confirm the tests are still failing when run locally. Postponing for v1.2.3 then. If you'll find time to fix the tests, then this will come into the next-next bug fix release. If you don't find time to fix the tests, and if the tests for `legacy` branch are passing, then we should postpone for v1.3.0. (Please amend the milestone accordingly.)

**Pull request closed without merging**
