### PR TITLE
OAIRepository: marcxml output format

### LINKED ISSUE #2962: config: Wrong default OAI Repository metadata formats
I think the default config ```CFG_OAI_METADATA_FORMATS``` in ```invenio/base/config.py```

```
CFG_OAI_METADATA_FORMATS = {
    'oai_dc': ('XOAIMARC', 'http://www.openarchives.org/OAI/1.1/dc.xsd',
                           'http://purl.org/dc/elements/1.1/'),
    'marcxml': ('XOAIDC',
                'http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd',
                'http://www.loc.gov/MARC21/slim'),
}
```

Aren't the keys of the dictionary wrong?

### PR DESCRIPTION
**Pull request by jgarcial**
* FIX Switched names in config. (closes #2962)

* FIX Dummy variable not needed causing and error.

Signed-off-by: Jaime García <jaime.garcia.llopis@gmail.com>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@jgarcial thanks! Can you please amend commit message:
```
oairepository: fix marcxml output format

* FIX Switches keys in CFG_OAI_METADATA_FORMATS configuration mapping.
  (closes #2962)

* FIX Amends bfe_oai_marcxml element since get_preformatted_record
  does not return a tuple anymore.

Signed-off-by: Jaime García <jaime.garcia.llopis@gmail.com>
Reviewed-by: Jiri Kuncar <jiri.kuncar@cern.ch>
...

**Comment by jirikuncar** [comment]
ping @jgarcial

**Comment by jgarcial** [comment]
@jirikuncar 
I just rebased and pushed the amended commit.

**Comment by jirikuncar** [comment]
@jgarcial thanks!

**Pull request merged**
