### PR TITLE
installation: fix prerequisite package versions

### PR DESCRIPTION
**Pull request by tiborsimko**
* FIX Adds upper limit on versions of several prerequisite packages,
  fixing newly observed Invenio 2.0 demo site installation troubles.

Reported-by: Dmitri Pisarev <dimaip@gmail.com>
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
This should fix the installation troubles observed recently by @dimaip.

(CC-ing also @pamfilos who experienced CERN Open Data installation troubles lately as well.)

**Comment by dimaip** [comment]
@tiborsimko thanks a lot for the fix! It fixed the web container, but the worker is still failing.

**Comment by dimaip** [comment]
Ah no, my fault, forgot to kill old image. Testing...

**Comment by dimaip** [comment]
:+1: Verified.
Thanks a lot for taking care!

**Comment by pamfilos** [comment]
+1: Works for me..Thank you @tiborsimko

**Comment by egabancho** [comment]
:dancer:

**Comment by tiborsimko** [comment]
Changing to WIP while trying to get all the Travis tests pass...

**Pull request merged**
