### PR TITLE
bibcirculation: Adds ILL and purchase confirmation

### PR DESCRIPTION
**Pull request by mvesper**
* Adds e-mail confirmation to the user when an ILL or purchase request
  is performed.

Signed-off-by: Martin Vesper <martin.vesper@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@mvesper you might want to set your email address for git: `git config user.email mvesper@example.com`.

**Comment by kaplun** [comment]
Who from CDS is reviewing this branch? @switowski, @egabancho? TIND?

**Comment by egabancho** [comment]
We tested it on CDSTest, it worked as it was supposed to and we deployed it on CDS

**Comment by tiborsimko** [comment]
Thanks, merged as 11a1f019814f4554ea03fe5d92b01e8726fa1c2d.

**Pull request closed without merging**
