### PR TITLE
legacy: BibMatch removal

### PR DESCRIPTION
**Pull request by kaplun**
* INCOMPATIBLE Removes legacy BibMatch module. (addresses #3233)

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
@jalavik I guess we can happily kill bibmatch, right?

**Comment by jalavik** [comment]
@kaplun :+1:

**Comment by jirikuncar** [comment]
please rebase. thanks

**Comment by kaplun** [comment]
Done

**Pull request merged**
