### PR TITLE
docs: OS X installation guide improvements

### PR DESCRIPTION
**Pull request by jochenklein**

### CODE REVIEW

**Comment by jirikuncar** [comment]
@jochenklein is it only for `master` or also for `maint-2.0`?

**Comment by jochenklein** [comment]
Currently, the LZMA serializer is used in `master` only. But it will be necessary for `maint-2.0` at some point, too (if it gets merged).

**Comment by jirikuncar** [comment]
Let's keep it for `master` only.

**Comment by jirikuncar** [comment]
@jochenklein can you please rebase the PR? Thanks

**Comment by jochenklein** [comment]
Done.

**Comment by jirikuncar** [comment]
Can you please amend commit message:
```
* Adds XZ utils because LZMA serializer was added in #FIXME add sha1 of the commit
  and it might be missing on OS X.
```
or
```
* Adds XZ utils because LZMA serializer was added it might be
  missing on OS X. (addresses #3158)
```

**Pull request merged**
