### PR TITLE
global: "good luck" to "happy hacking"

### PR DESCRIPTION
**Pull request by tiborsimko**
* Rewords "Good luck" to "Happy hacking" in older maintenance branches
  as well.

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
Reviewed-by: Ludmila Marian <ludmila.marian@gmail.com>

### CODE REVIEW

**Comment by dset0x** [comment]
`s/choosing/flying/g`? :smile:

**Comment by tiborsimko** [comment]
@dset0x Yeah, wouldn't be bad either :smile: So far I'm just standardising on the same text we use elsewhere, also for older Invenio v1.x releases that are imminent... but perhaps we can start flying already.

**Comment by ludmilamarian** [comment]
:shipit:

**Comment by kaplun** [comment]
:dancer:

**Pull request merged**
