### PR TITLE
MiscUtils: urlutils: escape unsafe characters

### PR DESCRIPTION
**Pull request by drjova**
* Adds escaping url from unsafe characters.

* Updates bibdocfile templates.

Signed-off-by: Harris Tzovanakis <me@drjova.com>

### CODE REVIEW

**Comment by kaplun** [comment]
@drjova if this is needed to put a URL inside an `src` HTML attribute it should be enough to use standard `cgi.escape(url, quote=True), isn't it? That's how it is done everywhere else in Invenio...

**Comment by drjova** [comment]
@kaplun  Unfortunately `cgi.escape` is not enough for our case which some files have spaces in their file name.

``` python

>> a = "hello is it me that looking for"
>> In [1]: cgi.escape(a, quote=True)
>> Out[1]: 'hello is it me that looking for'
>> In [2]: quote(b, safe="%/:=&?~#+!$,;'@()*[]")
>> Out[2]: 'hello%20is%20it%20me%20that%20looking%20for'
```

I couldn't find anything similar in the invenio utils :/

**Comment by kaplun** [comment]
Good point. But then it would be better to correct this centrally. I.e. in `bibdocfile.BibDocFile.__init__()` where these URLs are generated. In this way all the places were BibDocFile URLs are used are going to see the correct version (e.g. when they are written in MARCXML, etc.)

This happens in https://github.com/inveniosoftware/invenio/blob/maint-1.2/modules/bibdocfile/lib/bibdocfile.py#L2977-L2982

**Comment by drjova** [comment]
:+1: I'll prepare a PR

**Comment by drjova** [comment]
PR#2908

**Comment by kaplun** [comment]
@drjova can we close this PR, as superseeded by #2908?

**Comment by drjova** [comment]
@kaplun yes!  

superseeded-by https://github.com/inveniosoftware/invenio/pull/2908

**Pull request closed without merging**
