### PR TITLE
accounts: typo in `repeat_email_validator`

### PR DESCRIPTION
**Pull request by giannistsan**
Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
Thanks @giannistsan! Can you please rebase this PR on top of `maint-2.0`?

**Comment by giannistsan** [comment]
@jirikuncar  This problem doesn't seem to exist in main-2.0.

**Comment by jirikuncar** [comment]
My fault - it should have been `maint-2.1`.

**Comment by jirikuncar** [comment]
@giannistsan there is no need to open new PR. You can force push to the same branch and integrators merge it to the correct branch.

--
cc @kaplun

**Comment by giannistsan** [comment]
@jirikuncar  Should the one in master be removed and only keep the one in maint-2.1 ?

**Comment by jirikuncar** [comment]
@giannistsan patches get applied to lowest possible maintenance branch, which is later merged to master. Hence please keep only PR for `maint-2.1` open. Let @kaplun to explain you Invenio contribution workflow or read http://invenio.readthedocs.org/en/latest/developers/git-workflow.html#understanding-official-repo-branches.

**Pull request closed without merging**
