### PR TITLE
travis: unittest2 requirements fix

### LINKED ISSUE #2862: global: jinja2hacks are causing troubles on Python 2.7.9
see for example https://travis-ci.org/inveniosoftware/invenio/builds/53365855

#### Workaround

Disable `invenio.ext.jinja2hacks` in `EXTENSIONS`.

--
cc @hachreak

### PR DESCRIPTION
**Pull request by hachreak**
* FIX Fixes TypeError error on markupsafe library. (closes #2862)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@hachreak shall we integrate it to maint-2.0 too?

**Comment by hachreak** [comment]
ping @jirikuncar

**Comment by tiborsimko** [comment]
BTW this commit adds `unittest2` only to Travis, while developers using Python 2.7.9 locally may also be bitten by this error the first time they run the tests?  It may be better to add a hack to `setup.py` too, though `unittest2` is already in `tests_require` there...

**Comment by hachreak** [comment]
@tiborsimko The error was not correlated with the python version.
See my [last comment](https://github.com/inveniosoftware/invenio/issues/2862#issuecomment-90508434) (and maybe the issue that I linked).

**Comment by tiborsimko** [comment]
> The error was not correlated with the python version.

OK.  We started to see it the problem at the time of the Python version upgrade, I think.  

Anyway, my main point was that this branch fixes Travis configuration only, while non-Travis users may also see the problem if they don't have `unittest2` previously installed...

**Pull request merged**
