### PR TITLE
WIP WebSearch: initial SRU support

### LINKED ISSUE #1153: SRU service implementation
Originally by *vbanos* on 2012-08-21

We are implementing SRU (http://www.loc.gov/standards/sru/) API support for Invenio ( (http://invenio-software.org/wiki/Talk/WebAPIs).

In a few words, SRU requests are sent via HTTP URLs and responses are XML documents. There are three main commands: explain, searchRetrieve and scan.
* **explain** provides repository information
* **searchRetrieve** is about searching and retrieve metadata records
* **scan** is used to request a range of the available terms at a given point within a list of indexed terms

We have already implemented explain and searchRetrieve.

We have two remaining issues to complete our task:
* scan command requires query parameters formatted in CQL language (http://www.loc.gov/standards/sru/specs/cql.html). We have found a python library that parses CQL and generates a tree http://srw.cheshire3.org/downloads/ but we don't know how to generate an invenio query from the tree. Any ideas?
* searchRetrieve and scan commands query all records and return metadata as results. Is it necessary to do any security/authentication checks before returning the results?

### PR DESCRIPTION
**Pull request by kaplun**
* Implements initial SRU support including CQL parser.
  (closes #1153)

Signed-off-by: Jerome Caffaro <jerome.caffaro@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
@kaplun Please attribute wanted milestone.

**Comment by kaplun** [comment]
This is more of interest to TIND. @Kennethhole this is what I was mentioning you today IRL. But it's implementing (for master only) the server-side, i.e. when Invenio has to be queried for ILL by another library.

**Comment by Kennethhole** [comment]
Thanks @kaplun ! I will have a look at it together with @audub

**Comment by kaplun** [comment]
Hi, I think this PR can be safely closed as someday as it is anyway to be reimplemented properly for master.

**Pull request closed without merging**
