### PR TITLE
Better records.js bundle and other related fixes

### PR DESCRIPTION
**Pull request by greut**
* Remove the cloudconnector from a record view
* Rename cloudconnector icon to its correct name
* Reduce records.js bundle file size by 100%
* Massive JavaScript refactoring and bug fix as the tabs were not properly working when using the `history.back()` button of the browser
* Fixes tind/base-overlay#92

### CODE REVIEW

**Comment by greut** [comment]
@jirikuncar ping, thanks.

**Comment by jirikuncar** [comment]
@greut remove -> removal, sykdrive -> skydrive + labels for release notes so people know what has changed and was fixed. Thanks

**Comment by greut** [comment]
@jirikuncar 

```
Improved features
-----------------

- Refactors the record.js code handling tabs.
- Reduces the records.js bundle file size.

Bug fixes
---------

- Fixes the information tab of a record doing nothing when another tab
  had been loaded.

Notes
-----

- Removes the cloudconnector modal view from a record.
```

**Comment by jirikuncar** [comment]
@greut can you also improve the titles of commit messages? Thanks

**Comment by greut** [comment]
better?

**Pull request merged**
