### PR TITLE
docker: more complete overlay documentation

### PR DESCRIPTION
**Pull request by tiborsimko**
* BETTER Improves Docker documentation notably related to how to work
   with Invenio site overlays.
    
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
Reviewed-by: Marco Neumann <marco@crepererum.net>

### CODE REVIEW

**Comment by tiborsimko** [comment]
See also https://github.com/inveniosoftware/invenio-demosite/pull/69.

**Comment by crepererum** [comment]
This was rejected the first time I've tried it. You have to set this specific config using an ENV variable.

**Comment by crepererum** [comment]
Not required as of https://github.com/inveniosoftware/invenio/blob/master/docker-compose-dev.yml#L46

**Comment by tiborsimko** [comment]
Indeed, the `CFG_DATABASE_HOST` bit is not needed, after rerunning. I had a case during weekend where the app couldn't connect to DB, and this fixed it; but it was perhaps caused by that `../invenio/invenio` mismatch that  mentioned at `https://github.com/inveniosoftware/invenio-demosite/pull/69#issuecomment-118839838` and that I've been tracking at the same time.

Anyway, is there an advantage in keeping `CFG_REDIS_HOSTS` in but `CFG_REDIS_HOSTS` out?  It would be nice to treat them similarly, for consistency...

**Comment by crepererum** [comment]
I'm currently doing some Docker work anyway, so I will try to isolate `CFG_REDIS_HOSTS` as well.

**Comment by tiborsimko** [comment]
> CFG_REDIS_HOSTS

OK, I'll then remove the `CFG_DATABASE_HOST` part and keep only the documentation amendments.

**Comment by crepererum** [comment]
:+1:

**Pull request merged**
