### PR TITLE
logging: fix sentry proxy

### PR DESCRIPTION
**Pull request by switowski**
* Fixes a typo in sentry.py (app.extensions, not extension).

Signed-off-by: Sebastian Witowski <sebastian.witowski@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@switowski please rebase it for `maint-2.0` and amend commit message headline. If you think it should be mentioned in RELEASE-NOTES add `FIX` label to your bullet point. Thanks

**Comment by switowski** [comment]
@jirikuncar done

**Comment by jirikuncar** [comment]
@switowski please remove commits that are not yours

**Comment by switowski** [comment]
@jirikuncar I have fixed the copyright year

**Pull request merged**
