### PR TITLE
deposit: better doi validation in edit form

### PR DESCRIPTION
**Pull request by bouzlibop**
* Adds validation to prevent removal of existing doi. (addresses zenodo/zenodo#231)

Signed-off-by: Adrian Pawel Baran <adrian.pawel.baran@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@bouzlibop did you want to address zenodo issue (`zenodo/zenodo#231`)?

**Comment by bouzlibop** [comment]
Yes, exactly, I forgot about this. Thanks @jirikuncar

**Comment by jirikuncar** [comment]
@bouzlibop can you rebase on top of `maint-2.0`?

**Comment by bouzlibop** [comment]
@jirikuncar done. Now I'm on top of `maint-2.0`.

**Pull request merged**
