### PR TITLE
OAIHarvest: harvesting "from beginning" fix

### PR DESCRIPTION
**Pull request by jalavik**
* Fixes an exception that would happen upon the initial harvest
  of a new OAI harvest source marked to be harvested "from beginning".

Reported-by: Jean-Yves Le Meur <Jean-Yves.Le.Meur@cern.ch>
Signed-off-by: Jan Aage Lavik <jan.age.lavik@cern.ch>

### CODE REVIEW

**Comment by jalavik** [comment]
@tiborsimko OAI harvesting "from beginning" has been broken for a while and this is the fix - dunno if it will make for the next release, so I put it in 1.3 for now..

**Comment by kaplun** [comment]
The code looks good!

**Comment by tiborsimko** [comment]
- [ ] Please update the commit log message to put the FIX label in front, so that this will be well reported in the automatically generated release notes.
- [ ] Please add `Reviewed-by: Samuele Kaplun <samuele.kaplun@cern.ch>`

**Comment by jalavik** [comment]
@tiborsimko Done!

**Comment by tiborsimko** [comment]
Thanks, merged as 3909c539f58f3b1cafd2823261fd57c42558e64d.

**Pull request closed without merging**
