### PR TITLE
WebSearch: tabs miss language parameter

### LINKED ISSUE #308: WebSearch: detailed record page tabs miss language parameter in CFG_SITE_LANG
Originally on 2010-10-11

Tabs ("References", "Discussion", etc.) on detailed record pages miss on purpose the 'ln=XX' parameter when the page is viewed in language 'CFG_SITE_LANG' (for eg: http://invenio-demo.cern.ch/record/96?ln=en): the consequence is that the browser preferred language is used when clicking on these tabs even if the user has specifically chosen to view the detailed page in language 'CFG_SITE_LANG'.

'ln=XX' should now be added whatever the value of 'CFG_SITE_LANG' is (in search_engine.py).

### PR DESCRIPTION
**Pull request by drjova**
- FIX Adds the proper language parameter on tabs if the user has
  selected different language from the browser preferred. (closes
  #308)

Signed-off-by: Harris Tzovanakis me@drjova.com

### CODE REVIEW

**Comment by drjova** [comment]
https://github.com/CERNDocumentServer/invenio/pull/128

**Comment by drjova** [comment]
ping @egabancho

**Comment by tiborsimko** [comment]
`maint-1.2` or `legacy`?  I guess this could be rebased against the former...

**Comment by tiborsimko** [comment]
Closed by https://github.com/inveniosoftware/invenio/pull/3728.

**Pull request closed without merging**
