### PR TITLE
legacy removal

### PR DESCRIPTION
**Pull request by hachreak**
* INCOMPATIBLE Removes mimetype, crossref, plotextractor utilities and
  ckeditor, bibexport, bibupload, encoder, bibconvert, converter modules.
 (addresses #3233)

### CODE REVIEW

**Comment by jmartinm** [comment]
You've come with energy after the holidays @hachreak :P

**Comment by hachreak** [comment]
batteries completely recharged! XD

**Comment by hachreak** [comment]
ping @jirikuncar

**Comment by jirikuncar** [comment]
Solved in Invenio 3.0.0a1.

**Pull request closed without merging**
