### PR TITLE
pdfchecker: module removal

### PR DESCRIPTION
**Pull request by kaplun**
* INCOMPATIBLE Removes legacy pdfchecker module together with ported
  'pdfchecker' module.  (addresses #3233)

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
I guess I should leave intact the upgrade recipe that at some point was creating the tables needed by pdfchecker.

**Comment by jirikuncar** [comment]
> I should leave intact the upgrade recipe

Yes. You can also remove the model so for new installations the tables are not created. When new module is ready it can do migration if the old tables still exists in db (`op.has_table(...)`).

**Comment by kaplun** [comment]
OK. Then I think it is got for integration.

**Comment by jirikuncar** [comment]
@kaplun please rebase ... thanks

**Comment by kaplun** [comment]
...aaaaaand done.

**Pull request merged**
