### PR TITLE
DocExtract: several improvements

### LINKED ISSUE #959: Fuzzy matching of book titles in refextract
Originally by _[adeiana (@Osso)](https://github.com/Osso)_ on 2012-03-22

### PR DESCRIPTION
**Pull request by kaplun**
* Accepts Publications as reference section.

* Refactors book handling and search.
  (closes #959)

* Daemon extracts all added pdfs.

* Correctly handles PDF/A files.

* Adds LIGO and LHCP report numbers to the kb.

* Adds the filename of the extracted files in the 999C6f field.

* Converts arxiv urls to report numbers

* Adds support for hdl identifiers.

* Sets a priority on which title form is the most important.
  References will be given priority over anything else while Reference
  will rank last with Bibliography in between.
  That means that if "Bibliography" is found in the text, we assume it is
  the reference section and we don't look for a section titles "Reference".

* Improves error message when pdftotext is missing.

Signed-off-by: Alessio Deiana <alessio.deiana@cern.ch>
Tested-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
Note the kwalitee is failing on copyright year, but when I originally made the PR they were correct (2014). Should I really go and amend all 15 files to write copyright 2015 (even if no change happened in 2015?)

**Comment by kaplun** [comment]
@tiborsimko this could be integrated into 1.2

**Comment by jirikuncar** [comment]
> Should I really go and amend all 15 files to write copyright 2015 (even if no change happened in 2015?)

This is bug. Could you please report it to [`kwalitee`](https://github.com/jirikuncar/kwalitee) package? Thanks

**Comment by kaplun** [comment]
> This is bug. Could you please report it to kwalitee package? Thanks

It's actually more funny: although the PR was made in 2014, and refreshed in 2015, the single commit is dated back to 2013 :dancer:

**Comment by kaplun** [comment]
This is superseded by https://github.com/inspirehep/refextract

**Pull request closed without merging**
