### PR TITLE
workflows: correspond object state names with docs

### PR DESCRIPTION
**Pull request by dset0x**
* Fix reference to `completed_objects` in the documentation (was:
  `final_objects` in code).

* Expose all other states via the `BibWorkflowEngine` interface and
  expand documentation.

### CODE REVIEW

**Comment by jirikuncar** [comment]
@dset0x please ping me when you rebase. Thanks!

**Comment by dset0x** [comment]
@jirikuncar Rebased.

**Comment by jirikuncar** [comment]
Please fix:
- http://kwalitee.invenio-software.org/inveniosoftware/invenio/commits/ca2aa29197aa46aa2cb1cac4946838fc39c260f4/
- http://kwalitee.invenio-software.org/inveniosoftware/invenio/commits/fea08c0ce1ba91ae4f03868cdb5712ce95ea6c5f/

You should probably add @jalavik as reviewer.

**Comment by dset0x** [comment]
@jirikuncar @jalavik has not reviewed the current version of this patch, but he should be able to tomorrow.

**Comment by jalavik** [comment]
@dset0x Looks good!

**Comment by dset0x** [comment]
@jirikuncar Should be good to merge now.

**Comment by dset0x** [comment]
@jirikuncar You mean only imperative mood in the first line, correct?

**Comment by jirikuncar** [comment]
@dset0x http://invenio.readthedocs.org/en/latest/developers/git-workflow.html?highlight=commit%20message#r2a-commit-message-format

**Comment by tiborsimko** [comment]
@dset0x The reason being that release notes such as:

- https://raw.githubusercontent.com/inveniosoftware/invenio/v1.1.4/RELEASE-NOTES

are being compiled automatically from commit headlines.  Hence the consistent module naming in front, hence preferring nouns when possible  (e.g. "faster foo" rather than "speeded up foo").

**Comment by dset0x** [comment]
Commit message problems fixed and branch rebased.

**Comment by jirikuncar** [comment]
@dset0x PR looks good. Please rebase. Thanks

**Pull request merged**
